import os
import subprocess
import tempfile
import random
import string
from github import Github

def generate_random_string(length=6):
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))

def create_github_pr(repo_name: str, base_commit: str, patch_code: str, title: str, description: str) -> str:
    """
    Clones the repo, applies the unified diff patch, pushes a new branch, and creates a Pull Request.
    """
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("[WARNING] GITHUB_TOKEN not properly configured. Returning mock PR link.")
        return "https://github.com/mock-repo/pull/1"

    print(f"[{repo_name}] Authenticating with GitHub...")
    g = Github(token)
    try:
        repo = g.get_repo(repo_name)
    except Exception as e:
        print(f"[ERROR] Could not access repo {repo_name} via PyGithub: {e}")
        return "#"

    clone_dir = tempfile.mkdtemp()
    auth_url = f"https://{token}@github.com/{repo_name}.git"
    branch_name = f"agentic-repair-{base_commit[:7]}-{generate_random_string()}"

    try:
        print(f"[{repo_name}] Cloning repository...")
        subprocess.run(["git", "clone", "--quiet", auth_url, clone_dir], check=True)
        
        print(f"[{repo_name}] Creating and checking out branch {branch_name}...")
        # Branch off the latest default branch so the patch applies against current code
        default_branch = repo.default_branch
        subprocess.run(["git", "checkout", default_branch], cwd=clone_dir, check=True)
        subprocess.run(["git", "checkout", "-b", branch_name], cwd=clone_dir, check=True)
        
        patch_path = os.path.join(clone_dir, "fix.patch")
        with open(patch_path, "w") as f:
            f.write(patch_code + "\n")
            
        print(f"[{repo_name}] Applying agent's patch...")
        apply_res = subprocess.run(["git", "apply", "--ignore-whitespace", "--ignore-space-change", "--recount", "fix.patch"], cwd=clone_dir)
        if apply_res.returncode != 0:
            print(f"[{repo_name}] git apply failed, trying with --3way...")
            apply_3way = subprocess.run(["git", "apply", "--ignore-whitespace", "--recount", "--3way", "fix.patch"], cwd=clone_dir)
            if apply_3way.returncode != 0:
                print(f"[{repo_name}] 3way failed too, falling back to 'patch -p1' utility...")
                subprocess.run(f"patch -p1 --force < fix.patch", shell=True, cwd=clone_dir)

        # Optional: cleanup the patch file so it doesn't get committed
        os.remove(patch_path)

        subprocess.run(["git", "config", "user.name", "Agentic CI/CD Bot"], cwd=clone_dir)
        subprocess.run(["git", "config", "user.email", "agentic-bot@hacktofuture.com"], cwd=clone_dir)
        
        subprocess.run(["git", "add", "."], cwd=clone_dir, check=True)
        # Verify if there's anything to commit
        status_res = subprocess.run(["git", "status", "--porcelain"], cwd=clone_dir, capture_output=True, text=True)
        if not status_res.stdout.strip():
            print(f"[{repo_name}] No actual changes resulted from patch.")
            return "#no-changes"

        subprocess.run(["git", "commit", "-m", title], cwd=clone_dir, check=True)
        
        print(f"[{repo_name}] Pushing to origin {branch_name}...")
        subprocess.run(["git", "push", "origin", branch_name], cwd=clone_dir, check=True)
        
        print(f"[{repo_name}] Creating Pull Request...")
        pr = repo.create_pull(
            title=title,
            body=description + "\n\n**Automated PR**: Generated by the Agentic CI/CD Repair Pipeline.",
            head=branch_name,
            base=repo.default_branch
        )
        return pr.html_url
        
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Subprocess Git command failed: {e}")
        return "#git-error"
    except Exception as e:
        print(f"[ERROR] Error creating PR: {e}")
        return "#error"

def apply_and_commit_to_main(repo_name: str, base_commit: str, patch_code: str, title: str, description: str) -> str:
    """
    Clones the repo, applies the patch, and pushes directly to the main branch.
    """
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("[WARNING] GITHUB_TOKEN not properly configured. Returning mock commit URL.")
        return "https://github.com/mock-repo/commit/mock_hash"

    print(f"[{repo_name}] Authenticating with GitHub for direct commit...")
    clone_dir = tempfile.mkdtemp()
    auth_url = f"https://{token}@github.com/{repo_name}.git"

    try:
        print(f"[{repo_name}] Cloning repository...")
        subprocess.run(["git", "clone", "--quiet", auth_url, clone_dir], check=True)
        
        # Ensure we target the repository's default/main branch
        g = Github(token)
        repo = g.get_repo(repo_name)
        default_branch = repo.default_branch
        
        subprocess.run(["git", "checkout", default_branch], cwd=clone_dir, check=True)
        
        patch_path = os.path.join(clone_dir, "fix.patch")
        with open(patch_path, "w") as f:
            f.write(patch_code + "\n")
            
        print(f"[{repo_name}] Applying agent's patch to {default_branch}...")
        apply_res = subprocess.run(["git", "apply", "--ignore-whitespace", "--ignore-space-change", "--recount", "fix.patch"], cwd=clone_dir)
        if apply_res.returncode != 0:
            print(f"[{repo_name}] Strict git apply failed, falling back to 'patch -p1' utility...")
            subprocess.run(f"patch -p1 --force < fix.patch", shell=True, cwd=clone_dir)

        os.remove(patch_path)

        subprocess.run(["git", "config", "user.name", "Agentic CI/CD Bot"], cwd=clone_dir)
        subprocess.run(["git", "config", "user.email", "agentic-bot@hacktofuture.com"], cwd=clone_dir)
        
        subprocess.run(["git", "add", "."], cwd=clone_dir, check=True)
        status_res = subprocess.run(["git", "status", "--porcelain"], cwd=clone_dir, capture_output=True, text=True)
        if not status_res.stdout.strip():
            print(f"[{repo_name}] No actual changes resulted from patch.")
            return "#no-changes"

        commit_msg = f"{title}\n\n{description}\n\nAutomated fix proposed and approved via Agentic CI/CD Repair Pipeline."
        subprocess.run(["git", "commit", "-m", commit_msg], cwd=clone_dir, check=True)
        
        print(f"[{repo_name}] Pushing strictly to origin {default_branch}...")
        subprocess.run(["git", "push", "origin", default_branch], cwd=clone_dir, check=True)
        
        # Ascertain the newest commit SHA to return
        latest_hash = subprocess.run(["git", "rev-parse", "HEAD"], cwd=clone_dir, capture_output=True, text=True, check=True).stdout.strip()
        commit_url = f"https://github.com/{repo_name}/commit/{latest_hash}"
        return commit_url
        
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Subprocess Git command failed: {e}")
        return "#git-error"
    except Exception as e:
        print(f"[ERROR] Error committing to main: {e}")
        return "#error"
